new pipelines synatax

diff --git a/scripts/install-secret b/scripts/install-secret
--- a/scripts/install-secret
+++ b/scripts/install-secret
@@ -1,8 +1,7 @@
-DOCKERHUB_USERNAME=$MY_DOCKER_USER
-DOCKERHUB_PASSWORD=$MY_DOCKER_PW
 
-GITHUB_USERNAME=$MY_PUBLIC_GIT_USER
-GITHUB_TOKEN=$MY_PUBLIC_GIT_TOKEN
+## docker-push secret used to push images to dockerhub
+## git secret used to login to private git reps
+
 GITHUB_URL=https://github.com
 
 IS_DOCKER_DESKTOP=$(kubectl config current-context)
@@ -13,6 +12,12 @@ else
 DASHBOARD_HOST=https://despond1.fyre.ibm.com
 fi
 
+echo DASHBOARD is $DASHBOARD_HOST
+
+URL=$DASHBOARD_HOST/proxy/api/v1/namespaces/$TEKTON_DEMO_NS/secrets 
+
+echo Dashboard Secrets URL is = $URL
+
 curl -k -s -m 2 $DASHBOARD_HOST > /dev/null
 until [ $? -eq 0 ] ; do
     echo Waiting for $DASHBOARD_HOST
@@ -20,46 +25,82 @@ until [ $? -eq 0 ] ; do
     curl -k -s -m 2 $DASHBOARD_HOST > /dev/null
 done
 
+DOCKERUSER=$(echo -n ${MY_DOCKER_USER} | base64 )
+DOCKERPASS=$(echo -n ${MY_DOCKER_PW} | base64)
 
-## docker-push secret used to push images to dockerhub
-export DASHBOARD_INSTALL_NS=$TEKTON_DEMO_NS
-export DASHBOARD_INSTALL_SA=$TEKTON_DEMO_SA
-
-post_data='{
-    "name": "dockerhub-user-password",
-    "type": "userpass",
-    "username": "'"${DOCKERHUB_USERNAME}"'",
-    "password": "'"${DOCKERHUB_PASSWORD}"'",
-    "url": {"tekton.dev/docker-0": "https://index.docker.io/v1/"},
-    "serviceaccount": "'"${DASHBOARD_INSTALL_SA}"'"
+ post_data='{
+  "apiVersion": "v1",
+  "kind": "Secret",
+  "metadata": {
+     "name": "dockerhub-user-password",
+    "namespace": "'"${TEKTON_DEMO_NS}"'",
+    "annotations": { "tekton.dev/git-0": "https://index.docker.io/v1/" },
+    "labels": {
+      "serviceAccount": "'"${TEKTON_DEMO_SA}"'"
+    }
+  },
+  "data": {
+    "username": "'"${DOCKERUSER}"'",
+    "password": "'"${DOCKERPASS}"'"
+  },
+  "type": "kubernetes.io/basic-auth"
 }'
+ 
+ #"type": "userpass"
+
+echo docker secret registration
+
+echo $post_data | jq
+ 
 
 kubectl get secrets -n $TEKTON_DEMO_NS | grep dockerhub-user-password  > /dev/null
 if [ $? -eq 0 ] ; then
     echo  "docker user and password secret is installed"
 else 
-    curl -k -X POST --header Content-Type:application/json -d "$post_data" $DASHBOARD_HOST/v1/namespaces/${DASHBOARD_INSTALL_NS}/credentials
-    echo 'created dockerhub-user-password  secret' 
+     curl -k -X POST --header Content-Type:application/json -d "$post_data" $URL  
+     if [ $? -eq 0 ] ; then
+          echo 'created dockerhub-user-password  secret' 
+     else
+          echo 'FAILED created dockerhub-user-password  secret' 
+     fi
 fi
 
-post_data='{                                                                                                                      
-    "name": "github-user-password",                                                                                          
-    "type": "userpass",                                                                                                           
-    "username": "'"${GITHUB_USERNAME}"'",                                                                                         
-    "password": "'"${GITHUB_TOKEN}"'",                                                                                            
-    "url": {"tekton.dev/git-0": "'"${GITHUB_URL}"'"},                                                                             
-    "serviceaccount": "'"${DASHBOARD_INSTALL_SA}"'"
+GITUSER=$(echo -n ${MY_PUBLIC_GIT_USER} | base64 )
+GITPASS=$(echo -n ${MY_PUBLIC_GIT_TOKEN} | base64)
 
+ post_data='{
+  "apiVersion": "v1",
+  "kind": "Secret",
+  "metadata": {
+     "name": "github-user-password",
+    "namespace": "'"${TEKTON_DEMO_NS}"'",
+    "annotations": { "tekton.dev/git-0": "'"${GITHUB_URL}"'"},
+    "labels": {
+      "serviceAccount": "'"${TEKTON_DEMO_SA}"'"
+    }
+  },
+  "data": {
+    "username": "'"${GITUSER}"'",
+    "password": "'"${GITPASS}"'"
+  },
+  "type": "kubernetes.io/basic-auth"
 }'
+
+
+echo github secret registration
+
+echo $post_data | jq
 
 kubectl get secrets -n $TEKTON_DEMO_NS | grep github-user-password  > /dev/null
 if [ $? -eq 0 ] ; then
     echo  "git user and password secret is installed"
 else 
-    curl -k -X POST --header Content-Type:application/json -d "$post_data" $DASHBOARD_HOST/v1/namespaces/${DASHBOARD_INSTALL_NS}/\
-credentials
-    echo 'created github-user-password secret'
-
+    curl -k -X POST --header Content-Type:application/json -d "$post_data" $URL  
+    if [ $? -eq 0 ] ; then
+        echo 'created github-user-password secret'
+    else
+	    echo 'FAILED created github-user-password secret'
+    fi
 fi
 
 
